version: "3.9"

services:
  wp:
    build: ./bot
    env_file:
      - .env
    command: ["python", "main_wp.py"]
    volumes:
      - ./secrets:/secrets

  ig:
    build: ./bot
    env_file:
      - .env
    command: ["python", "main_ig.py"]
    volumes:
      - ./secrets:/secrets

  threads:
    build: .
    working_dir: /app/bot
    command: python3 threads_post.py
    env_file:
      - .env
    volumes:
      - ./:/app

